// Code generated by gobok v1.0.0. DO NOT EDIT.

package main

type PersonBuilder struct {
	instance Person
}

func NewPersonBuilder() *PersonBuilder {
	return &PersonBuilder{
		instance: Person{},
	}
}

func (b *PersonBuilder) SetName(v string) *PersonBuilder {
	b.instance.Name = v
	return b
}
func (b *PersonBuilder) SetAge(v int) *PersonBuilder {
	b.instance.Age = v
	return b
}
func (b *PersonBuilder) SetIsActive(v bool) *PersonBuilder {
	b.instance.IsActive = v
	return b
}
func (b *PersonBuilder) SetTags(v []string) *PersonBuilder {
	b.instance.Tags = v
	return b
}
func (b *PersonBuilder) SetMetadata(v map[string]interface{}) *PersonBuilder {
	b.instance.Metadata = v
	return b
}
func (b *PersonBuilder) SetParent(v *Person) *PersonBuilder {
	b.instance.Parent = v
	return b
}

func (b *PersonBuilder) Build() *Person {
	return &b.instance
}
